# Generated by Django 5.2.6 on 2025-11-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administer',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('sex', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('gpa', models.FloatField()),
            ],
        ),
    ]
