# Generated by Django 5.2.6 on 2025-11-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_student_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
