# Generated by Django 5.2.6 on 2025-11-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_student_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='army',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='competition',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='creation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='honor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='internship',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='sci_research',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='social',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='sport',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='volunteer',
            field=models.FloatField(default=0),
        ),
    ]
