# Generated by Django 5.2.6 on 2025-11-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_student_army_student_competition_student_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(default=0),
        ),
    ]
