# Generated by Django 5.2.6 on 2025-11-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_student_gpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='army',
        ),
        migrations.RemoveField(
            model_name='student',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='student',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='honor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='internship',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sci_research',
        ),
        migrations.RemoveField(
            model_name='student',
            name='social',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='student',
            name='volunteer',
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(default='major', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='username', max_length=20),
        ),
    ]
