# Generated by Django 5.2.6 on 2025-12-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_student_army_remove_student_competition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administer',
            name='sex',
        ),
    ]
