# Generated by Django 5.2.6 on 2025-12-21 04:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_administer_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(default='material_name', max_length=20)),
                ('material_type', models.CharField(default='material_type', max_length=20)),
                ('sci_research', models.FloatField(default=0)),
                ('competition', models.FloatField(default=0)),
                ('creation', models.FloatField(default=0)),
                ('internship', models.FloatField(default=0)),
                ('army', models.FloatField(default=0)),
                ('volunteer', models.FloatField(default=0)),
                ('honor', models.FloatField(default=0)),
                ('social', models.FloatField(default=0)),
                ('sport', models.FloatField(default=0)),
                ('last_upload_time', models.DateTimeField(default=datetime.datetime.now)),
                ('last_upload_day', models.DateField(default=datetime.datetime.now)),
                ('request_upload_time', models.DateTimeField(default=datetime.datetime.now)),
                ('request_upload_day', models.DateField(default=datetime.datetime.now)),
                ('review_upload_time', models.DateTimeField(default=datetime.datetime.now)),
                ('review_upload_day', models.DateField(default=datetime.datetime.now)),
                ('review_state', models.IntegerField(default=0)),
                ('failure_reason', models.CharField(default='material_type', max_length=200)),
                ('review_officer', models.CharField(default='material_type', max_length=20)),
                ('excepted_score', models.FloatField(default=0)),
                ('actual_score', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.student')),
            ],
        ),
    ]
