# Generated by Django 5.2.6 on 2025-12-21 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.student'),
        ),
    ]
