# Generated by Django 5.2.6 on 2025-12-21 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_material_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='army',
        ),
        migrations.RemoveField(
            model_name='material',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='material',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='material',
            name='honor',
        ),
        migrations.RemoveField(
            model_name='material',
            name='internship',
        ),
        migrations.RemoveField(
            model_name='material',
            name='sci_research',
        ),
        migrations.RemoveField(
            model_name='material',
            name='social',
        ),
        migrations.RemoveField(
            model_name='material',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='material',
            name='volunteer',
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sci_research', models.FloatField(default=0)),
                ('competition', models.FloatField(default=0)),
                ('creation', models.FloatField(default=0)),
                ('internship', models.FloatField(default=0)),
                ('army', models.FloatField(default=0)),
                ('volunteer', models.FloatField(default=0)),
                ('honor', models.FloatField(default=0)),
                ('social', models.FloatField(default=0)),
                ('sport', models.FloatField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.student')),
            ],
        ),
    ]
