# Generated by Django 5.2.6 on 2025-12-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_remove_material_army_remove_material_competition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_file',
            field=models.FileField(default='media/本科生请假单.docx', upload_to='', verbose_name='材料文件'),
        ),
    ]
